# Generated by Django 4.2.1 on 2023-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
